### ISSUE TITLE
Change folder structure

### ISSUE THREAD

**Issue by sathsarabandaraj** [Care-X/landing-page#1]
**Is your feature request related to a problem? Please describe.**
- No
 
**Describe the solution you'd like**
Change folder structure

**Describe alternatives you've considered**

**Additional context**
- Change folder structure as follows
      
- > landing-page/
      ├─ assets/
      │  ├─ css/
      │  │  ├─ custom.css
      │  ├─ js/
      │  ├─ img/
      │  ├─ src/
      ├─ index.html

**Comment by Hasthikagirihagama** [comment]
I will work on this issue @sathsarabandaraj
