### ISSUE TITLE
Nav links are not working properly

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#32]
**Describe the bug**
Currently, the nav links are not working properly.

**To Reproduce**
1. Go to 'landing-page'
2. Click on 'nav-links'

**Expected behavior**
Add an ID to each section and replace the id with the link in the nav item

**Additional context**

Are you working on it?
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
Ok

**Comment by YoshithaRathnayake** [comment]
> Ok

Thank You @SilunaP
