### ISSUE TITLE
Add are you working on it section to the bug report and feature request issue templates

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#33]
**Is your feature request related to a problem? Please describe.**
Currently, the Are you working on it section is missing in the issue templates

**Describe the solution you'd like**
Add are you working on it section to the bug report and feature request issue templates

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
Ok

**Comment by YoshithaRathnayake** [comment]
Thank You @SilunaP
