### ISSUE TITLE
Create a new button as download in the download section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#37]
**Is your feature request related to a problem? Please describe.**
Currently, there is no download button to download the app. It is linked to the nav link

**Describe the solution you'd like**
Remove the app download link from the nav link and create a new button as download in the download section and link it with the app download link

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok

**Comment by YoshithaRathnayake** [comment]
> ok

Thanks @SilunaP
