### ISSUE TITLE
Can't see the image in the footer

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#39]
**Describe the bug**
Currently, there is an image in the footer which we can't see it.

**To Reproduce**
1. Go to 'landing page'
3. Scroll down to 'footer'

**Expected behavior**
Correct the image link properly

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/199266890-9e94db0a-86e0-4ce6-997b-a564f4afafeb.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok

**Comment by YoshithaRathnayake** [comment]
> ok

Thank You @SilunaP
