### ISSUE TITLE
Blur the background of the navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#45]
**Is your feature request related to a problem? Please describe.**
Currently, its hard to read the nav items specially in the mobile view bcs it is transparent. We can see the moving objects in the background.

**Describe the solution you'd like**
Blur the background of the navbar

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
