### ISSUE TITLE
Add a gap between the nav logo and the nav links

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#47]
**Is your feature request related to a problem? Please describe.**
Currently, nav logo and nav links are in together.

**Describe the solution you'd like**
Add a gap between the nav logo and the nav links

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
