### ISSUE TITLE
Add a `Clone your forked repository` section to the readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#48]
**Is your feature request related to a problem? Please describe.**
Currently, there are no `clone your forked repository` section in the readme.md file

**Describe the solution you'd like**
Add a `Clone your forked repository` section to the readme.md file

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
