### ISSUE TITLE
Increase the height of the navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#52]
**Is your feature request related to a problem? Please describe.**
Currently, the navbar is too shorter

**Describe the solution you'd like**
Increase the height of the navbar

**Screenshot**
After the change

![image](https://user-images.githubusercontent.com/97069900/200112179-08d9c21c-9804-489f-b3de-7c3e57d8fac8.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
