### ISSUE TITLE
Decrease the margin of the bottom of the mobile navbar

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#53]
**Describe the bug**
Currently, the margin of the bottom of the navbar is increased

**Expected behavior**
Decrease the margin of the bottom of the mobile navbar

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/200112899-f764085f-c10b-4726-9b61-c4d026f00bb1.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
