### ISSUE TITLE
The menu icon and the nav items are sticked in the mobile view

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#62]
**Describe the bug**
Currently, The menu icon and the nav items are sticked in the mobile view

**Expected behavior**
Add margin top to the nav items or margin bottom to the menu icon

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/200118963-63b2c556-8986-4a17-9ee4-360ab69add77.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
