### ISSUE TITLE
Add a new comment on the Preview Link section

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#66]
**Is your feature request related to a problem? Please describe.**
Currently, the contributors don't know how to put the preview link in the PR Template

**Describe the solution you'd like**
Add a new comment on the Preview Link section describing how to put the preview link

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
