### ISSUE TITLE
The margin bottom of the nav items in the mobile view is increased

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#70]
**Describe the bug**
The margin bottom of the nav items in the mobile view is increased

**Expected behavior**
Decrease the margin bottom of the nav items in the mobile view

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/200185639-23039fb3-438e-4102-87de-47b14054a189.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
