### ISSUE TITLE
Reduce the margin left of the icon in the footer

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#71]
**Describe the bug**
Currently, the mail in the footer in the mobile view is breaking to two lines

**Expected behavior**
Reduce the margin left of the icon in the footer

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/200186179-b42abd2a-d435-4f05-8be7-410ae91239d5.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
