### ISSUE TITLE
Increase the margin bottom of the content of the footer

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#80]
**Describe the bug**
Currently, the content of the footer is aligned bit more to the bottom

**Expected behavior**
Increase the margin bottom of the content of the footer

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/200213188-a9427539-9df2-475e-a8e5-cf50a27a8c17.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
