### ISSUE TITLE
In the mobile view the title and the description is like same font size

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#82]
**Describe the bug**
Currently, In the mobile view the title and the description is like same font size

**Expected behavior**
Reduce the font size of the description

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/200279715-11b5b2df-2a6b-4535-beb6-22ba258b7819.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
