### ISSUE TITLE
Add a hover bold animation to the links in the Explore column in footer

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#83]
**Is your feature request related to a problem? Please describe.**
Currently, can't see the links in the Explore column in footer as links

**Describe the solution you'd like**
Add a hover bold animation to the links in the Explore column in footer

![image](https://user-images.githubusercontent.com/97069900/200307350-d4da4a46-7581-4943-a0fb-8b68643add1d.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by SilunaP** [comment]
ok
