### ISSUE TITLE
Fix the spelling mistake in the Git Commands section in readme.md file

### ISSUE THREAD

**Issue by YoshithaRathnayake** [Care-X/landing-page#91]
**Describe the bug**
Currently, there is a spelling mistake in the Git Commands section in the readme.md file

**To Reproduce**
1. Go to 'readme.md'
2. Scroll down to 'Git Commands'
3. See error

**Expected behavior**
Fix the spelling mistake in the Git Commands section in readme.md file

- It should be `git commit -m 'Your Message'`

**Screenshots**
![image](https://user-images.githubusercontent.com/97069900/216238232-b8a94ca9-0905-4057-81a4-1c5c0e2ab3ec.png)

**Are you working on it?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this?

**Comment by Prasadkpd** [comment]
@sathsarabandaraj Is this not assigned, shall I work on this?

**Comment by sathsarabandaraj** [comment]
Yeah.
Go ahead @Prasadkpd

**Comment by YoshithaRathnayake** [comment]
> Yeah. Go ahead @Prasadkpd

@sathsarabandaraj can you assign me for the other issues?
